# Generated by Django 4.0.6 on 2022-12-06 21:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=50, null=True, unique=True)),
                ('Titulo', models.CharField(blank=True, choices=[('Sr', 'Señor'), ('Sra', 'Señora'), ('Srita', 'Señorita'), ('Joven', 'Joven')], default='Sr.', max_length=50, null=True)),
                ('Apellido_Paterno', models.CharField(max_length=100)),
                ('Apellido_Materno', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('Domicilio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Ciudad', models.CharField(blank=True, default='CDMX', max_length=30, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo_1', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pacientes/fotos/%Y/%m/%d/')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('modificada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'pacientes',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Notas_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('imagen_5', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('imagen_6', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('imagen_7', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('imagen_8', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('imagen_9', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('imagen_10', models.ImageField(blank=True, null=True, upload_to='paciente_notas_extra')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('refiere', models.ForeignKey(help_text='seleccione el paciente que corresponde', on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'verbose_name_plural': 'Notas_Extra',
                'ordering': ('-id',),
                'get_latest_by': ['creada'],
            },
        ),
        migrations.CreateModel(
            name='Cuaderno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('estatura', models.CharField(blank=True, max_length=500, null=True)),
                ('peso', models.CharField(blank=True, max_length=500, null=True)),
                ('presion', models.CharField(blank=True, max_length=500, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=500, null=True)),
                ('toxicologico', models.CharField(blank=True, max_length=500, null=True)),
                ('interrogatorio', models.CharField(blank=True, max_length=500, null=True)),
                ('exploracion', models.CharField(blank=True, max_length=500, null=True)),
                ('estudios', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen_1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('imagen_2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('imagen_3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('imagen_4', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('imagen_5', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('imagen_6', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('imagen_7', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('imagen_8', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('imagen_9', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('imagen_10', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='paciente_notas_evolucion')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(help_text='seleccione el paciente que corresponde', on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'verbose_name_plural': 'Cuadernos',
                'ordering': ('-id',),
                'get_latest_by': ['creada'],
            },
        ),
    ]
