from django.db import models
from django import forms
from datetime import datetime
from imagekit.models import ProcessedImageField
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField


from paciente.models import Paciente
from persona.models import Persona


class Consulta(models.Model):

    COLUMNA_GENERAL_OPCIONES = (
    ('M99.1 - COMPLEJO DE SUBLUXACION VERTEBRAL', 'M99.1 - COMPLEJO DE SUBLUXACION VERTEBRAL'),
    ('1 - 922.31 - SECUNDARIO A DISFUNCIONES BIOMECÁNICAS DE LA COLUMNA VERTEBRAL', '1 - 922.31 - SECUNDARIO A DISFUNCIONES BIOMECÁNICAS DE LA COLUMNA VERTEBRAL'),
    ('2 - 922.31 - DISFUNCIÓN ARTICULAR Y MUSCULAR SIMPLES', '2 - 922.31 - DISFUNCIÓN ARTICULAR Y MUSCULAR SIMPLES'),
    ('3 - 922.31 - CONTUSIÓN AGUDA CON TRAUMA MENOR EN TEJIDOS BLANDOS', '3 - 922.31 - CONTUSIÓN AGUDA CON TRAUMA MENOR EN TEJIDOS BLANDOS'),
    ('4 - 922.31 - CONTUSIÓN AGUDA CON TRAUMA MODERADO EN TEJIDOS BLANDOS', '4 - 922.31 - CONTUSIÓN AGUDA CON TRAUMA MODERADO EN TEJIDOS BLANDOS'),
    ('5 - 922.31 - CONTUSIÓN AGUDA CON TRAUMA SEVERO EN TEJIDOS BLANDOS', '5 - 922.31 - CONTUSIÓN AGUDA CON TRAUMA SEVERO EN TEJIDOS BLANDOS'),
    ('6 - 922.31 - MIOFIBROSISTIS CRONICA', '6 - 922.31 - MIOFIBROSISTIS CRONICA'),
    )
    COLUMNA_CERVICAL_OPCIONES = (
    ('7 - 847.0, 839.08 - ESGUINCE CERVICAL AGUDO CON DESGARRO MUSCULAR Y SUBLUXACIONES FUNCIONALES DE', '7 - 847.0, 839.08 - ESGUINCE CERVICAL AGUDO CON DESGARRO MUSCULAR Y SUBLUXACIONES FUNCIONALES DE '),
    ('8 - 847.0, 839.08 - ESGUINCE CERVICAL AGUDO GRADO I Y SUBLUXACIONES FUNCIONALES DE', '8 - 847.0, 839.08 - ESGUINCE CERVICAL AGUDO GRADO I Y SUBLUXACIONES FUNCIONALES DE'),
    ('9 - 847.0, 839.08 - ESGUINCE CERVICAL AGUDO GRADO II Y SUBLUXACIONES FUNCIONALES DE', '9 - 847.0, 839.08 - ESGUINCE CERVICAL AGUDO GRADO II Y SUBLUXACIONES FUNCIONALES DE'),
    ('10 - 847.0, 839.08 - ESGUINCE CERVICAL AGUDO GRADO III Y SUBLUXACIONES FUNCIONALES DE', '10 - 847.0, 839.08 - ESGUINCE CERVICAL AGUDO GRADO III Y SUBLUXACIONES FUNCIONALES DE'),
    ('11 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL AGUDO ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '11 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL AGUDO ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('12 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CRÓNICO ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '12 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CRÓNICO ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('13 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CON INCIPIENTE ESPONDILOSIS SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '13 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CON INCIPIENTE ESPONDILOSIS SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('14 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOSIS SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '14 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOSIS SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('15 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '15 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('16 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '16 - 723.1, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('17 - 723.1, 839.08 - CERVICOBRAQUIALGIA AGUDA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '17 - 723.1, 839.08 - CERVICOBRAQUIALGIA AGUDA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('18 - 723.1, 839.08 - CERVICOBRAQUIALGIA AGUDA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '18 - 723.1, 839.08 - CERVICOBRAQUIALGIA AGUDA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('19 - 723.1, 839.08 - CERVICOBRAQUIALGIA AGUDA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '19 - 723.1, 839.08 - CERVICOBRAQUIALGIA AGUDA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('20 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL AGUDO', '20 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL AGUDO'),
    ('21 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL AGUDO CON ESPONDILOARTROSIS INCIPIENTE ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '21 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL AGUDO CON ESPONDILOARTROSIS INCIPIENTE ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('22 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL AGUDO CON ESPONDILOARTROSIS ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '22 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL AGUDO CON ESPONDILOARTROSIS ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('23 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL CRÓNICO CON ESPONDILOARTROSIS INCIPIENTE ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '23 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL CRÓNICO CON ESPONDILOARTROSIS INCIPIENTE ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('24 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL CRÓNICO CON ESPONDILOARTROSIS ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '24 - 723.1, 839.08 - SINDROME FACETARIO CERVICAL CRÓNICO CON ESPONDILOARTROSIS ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('25 - 723,4, 738.4, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOLISTESIS ADQUIRIDA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '25 - 723,4, 738.4, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOLISTESIS ADQUIRIDA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('26 - 723,4, 738.4, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOLISTESIS ADQUIRIDA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '26 - 723,4, 738.4, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOLISTESIS ADQUIRIDA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('27 - 723,4, 738.4, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOLISTESIS ADQUIRIDA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '27 - 723,4, 738.4, 839.08 - SINDROME DOLOROSO CERVICAL CON ESPONDILOLISTESIS ADQUIRIDA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('28 - 723.5, 839.08 - TORTÍCOLIS AGUDA Y SUBLUXACIONES FUNCIONALES DE', '28 - 723.5, 839.08 - TORTÍCOLIS AGUDA Y SUBLUXACIONES FUNCIONALES DE'),
    ('29 - 723.5, 839.08 - TORTÍCOLIS CRÓNICA ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '29 - 723.5, 839.08 - TORTÍCOLIS CRÓNICA ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('30 - 847.0, 839.08 - TORTÍCOLIS POSTRAUMÁTICA Y SUBLUXACIONES FUNCIONALES DE', '30 - 847.0, 839.08 - TORTÍCOLIS POSTRAUMÁTICA Y SUBLUXACIONES FUNCIONALES DE'),
    ('31 - 353.0, 839.08 - SÍNDROME DE LA SALIDA TORÁXICA AGUDO ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '31 - 353.0, 839.08 - SÍNDROME DE LA SALIDA TORÁXICA AGUDO ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('32 - 353.0, 839.08 - SÍNDROME DE LA SALIDA TORÁXICA CRÓNICO ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '32 - 353.0, 839.08 - SÍNDROME DE LA SALIDA TORÁXICA CRÓNICO ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('33 - 732,2, 839.08 - SÍNDROME CERVICO-CRANEAL (SÍNDROME SIMPÁTICO CERVICAL POSTERIOR) ASOCIADO A SUBLUXACIONES FUNCIONALES DE', '33 - 732,2, 839.08 - SÍNDROME CERVICO-CRANEAL (SÍNDROME SIMPÁTICO CERVICAL POSTERIOR) ASOCIADO A SUBLUXACIONES FUNCIONALES DE'),
    ('34 - 721.7, 839.08 - ESPONDILOPATÍA TRAUMÁTICA Y SUBLUXACIONES FUNCIONALES DE', '34 - 721.7, 839.08 - ESPONDILOPATÍA TRAUMÁTICA Y SUBLUXACIONES FUNCIONALES DE'),
    ('35 - 723.0, 721.90, 839.08 - ESTENOSIS CERVICAL SIN MIELOPATÍA', '35 - 723.0, 721.90, 839.08 - ESTENOSIS CERVICAL SIN MIELOPATÍA'),
    ('36 - 723.0, 721.91 - ESTENOSIS CERVICAL CON MIELOPATÍA', '36 - 723.0, 721.91 - ESTENOSIS CERVICAL CON MIELOPATÍA'),
    ('37 - 721.1, 722.71 - MIELOPATÍA ESPONDILÓTICA', '37 - 721.1, 722.71 - MIELOPATÍA ESPONDILÓTICA'),
    ('38 - 805.0 - FRACTURA (especificar el nivel vertebral)', '38 - 805.0 - FRACTURA (especificar el nivel vertebral)'),
    ('39 - 723.8, 839.08 - NEURALGIA OCCIPITAL CON SUBLUXACIONES ASOCIADAS', '39 - 723.8, 839.08 - NEURALGIA OCCIPITAL CON SUBLUXACIONES ASOCIADAS'),
    )
    TORAXICA_OPCIONES = (
    ('40 - 739.8 - SUBLUXACIÓN COSTOVERTEBRAL (indicar el nivel)', '40 - 739.8 - SUBLUXACIÓN COSTOVERTEBRAL (indicar el nivel)'),
    ('41 - 739.8 - ESGUINCE COSTOVERTEBRAL (indicar el nivel)', '41 - 739.8 - ESGUINCE COSTOVERTEBRAL (indicar el nivel)'),
    ('42 - 847.1, 839.21 - ESGUINCE TORÁXICO AGUDO CON LESIÓN DE TEJIDO MUSCULAR CON SUBLUXACIONES ASOCIADAS', '42 - 847.1, 839.21 - ESGUINCE TORÁXICO AGUDO CON LESIÓN DE TEJIDO MUSCULAR CON SUBLUXACIONES ASOCIADAS'),
    ('43 - 847.1, 839.21 - ESGUINCE TORÁXICO AGUDO GRADO I CON SUBLUXACIONES ASOCIADAS', '43 - 847.1, 839.21 - ESGUINCE TORÁXICO AGUDO GRADO I CON SUBLUXACIONES ASOCIADAS'),
    ('44 - 847.1, 839.21 - ESGUINCE TORÁXICO AGUDO GRADO II CON SUBLUXACIONES ASOCIADAS', '44 - 847.1, 839.21 - ESGUINCE TORÁXICO AGUDO GRADO II CON SUBLUXACIONES ASOCIADAS'),
    ('45 - 847.1, 839.21 - ESGUINCE TORÁXICO AGUDO GRADO III CON SUBLUXACIONES ASOCIADAS', '45 - 847.1, 839.21 - ESGUINCE TORÁXICO AGUDO GRADO III CON SUBLUXACIONES ASOCIADAS'),
    ('46 - 724.1, 839.21 - SINDROME DOLOROSO TORÁXICO AGUDO CON SUBLUXACIONES ASOCIADAS', '46 - 724.1, 839.21 - SINDROME DOLOROSO TORÁXICO AGUDO CON SUBLUXACIONES ASOCIADAS'),
    ('47 - 722.11, 839.21 - SINDROME DOLOROSO TORÁXICO CRÓNICO CON SUBLUXACIONES ASOCIADAS', '47 - 722.11, 839.21 - SINDROME DOLOROSO TORÁXICO CRÓNICO CON SUBLUXACIONES ASOCIADAS'),
    ('48 - 722.72, 839.21 - SINDROME DOLOROSO TORÁXICO CON INCIPIENTE ESPONDILOSIS SIN SIGNOS NEUROLOGICOS CON SUBLUXACIONES ASOCIADAS', '48 - 722.72, 839.21 - SINDROME DOLOROSO TORÁXICO CON INCIPIENTE ESPONDILOSIS SIN SIGNOS NEUROLOGICOS CON SUBLUXACIONES ASOCIADAS'),
    ('49 - 722.72, 839.21 - SINDROME DOLOROSO TORÁXICO CON ESPONDILOSIS SIN SIGNOS NEUROLOGICOS CON SUBLUXACIONES ASOCIADAS', '49 - 722.72, 839.21 - SINDROME DOLOROSO TORÁXICO CON ESPONDILOSIS SIN SIGNOS NEUROLOGICOS CON SUBLUXACIONES ASOCIADAS'),
    ('50 - 722.72, 839.21 - SINDROME DOLOROSO TORÁXICO CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS DEBILES CON SUBLUXACIONES ASOCIADAS', '50 - 722.72, 839.21 - SINDROME DOLOROSO TORÁXICO CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS DEBILES CON SUBLUXACIONES ASOCIADAS'),
    ('51 - 722.72, 839.21 - SINDROME DOLOROSO TORÁXICO CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS FRANCOS CON SUBLUXACIONES ASOCIADAS', '51 - 722.72, 839.21 - SINDROME DOLOROSO TORÁXICO CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS FRANCOS CON SUBLUXACIONES ASOCIADAS'),
    ('52 - 722.72 - MIELOPATÍA ESPONDILÓTICA', '52 - 722.72 - MIELOPATÍA ESPONDILÓTICA'),
    ('53 - 724.4, 839.21 - NEURITIS (INTERCOSTAL) CON SUBLUXACIONES ASOCIADAS', '53 - 724.4, 839.21 - NEURITIS (INTERCOSTAL) CON SUBLUXACIONES ASOCIADAS'),
    ('54 - 805.2 - FRACTURA DE COMPRESIÒN AGUDA (especificar nivel)', '54 - 805.2 - FRACTURA DE COMPRESIÒN AGUDA (especificar nivel)'),
    ('55 - 733.1 - COLAPSO VERTEBRAL AGUDO (especificar nivel)', '55 - 733.1 - COLAPSO VERTEBRAL AGUDO (especificar nivel)'),
    ('56 - 737.30 - ESCOLIOSIS IDIOPÁTICA', '56 - 737.30 - ESCOLIOSIS IDIOPÁTICA'),
    )
    LUMBO_SACRA_OPCIONES =(
    ('57 - 847.2 y 839.2 - ESGUINCE LUMBAR AGUDO, CON DESGARRO MUSCULAR CON SUBLUXACIONES ASOCIADAS', '57 - 847.2 y 839.2 - ESGUINCE LUMBAR AGUDO, CON DESGARRO MUSCULAR CON SUBLUXACIONES ASOCIADAS'),
    ('58 - 847.2 y 839.2 - ESGUINCE LUMBAR AGUDO GRADO I Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '58 - 847.2 y 839.2 - ESGUINCE LUMBAR AGUDO GRADO I Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('59 - 847.2 y 839.2 - ESGUINCE LUMBAR AGUDO GRADO II Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '59 - 847.2 y 839.2 - ESGUINCE LUMBAR AGUDO GRADO II Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('60 - 847.2 y 839.2 - ESGUINCE LUMBAR AGUDO GRADO III Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '60 - 847.2 y 839.2 - ESGUINCE LUMBAR AGUDO GRADO III Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('61 - 724.5 y 839.2 - SINDROME DOLOROSO LUMBAR AGUDO ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '61 - 724.5 y 839.2 - SINDROME DOLOROSO LUMBAR AGUDO ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('62 - 724.5 y 839.2 - SINDROME DOLOROSO LUMBAR CRÓNICO ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '62 - 724.5 y 839.2 - SINDROME DOLOROSO LUMBAR CRÓNICO ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('63 - 722.10 y 839.2 - SINDROME DOLOROSO LUMBAR CON INCIPIENTE ESPONDILOSIS SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '63 - 722.10 y 839.2 - SINDROME DOLOROSO LUMBAR CON INCIPIENTE ESPONDILOSIS SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('64 - 722.10 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOSIS SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '64 - 722.10 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOSIS SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('65 - 722.73 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '65 - 722.73 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('66 - 722.73 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '66 - 722.73 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOSIS CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('67 - 724.4 Y 839.2 - LUMBO-CIATICA AGUDA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '67 - 724.4 Y 839.2 - LUMBO-CIATICA AGUDA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('68 - 724.4 Y 839.2 - LUMBO-CIATICA AGUDA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '68 - 724.4 Y 839.2 - LUMBO-CIATICA AGUDA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('69 - 724.4 Y 839.2 - LUMBO-CIATICA AGUDA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '69 - 724.4 Y 839.2 - LUMBO-CIATICA AGUDA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('70 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR AGUDO', '70 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR AGUDO'),
    ('71 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR AGUDO CON ESPONDILOARTROSIS INCIPIENTE ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '71 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR AGUDO CON ESPONDILOARTROSIS INCIPIENTE ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('72 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR AGUDO CON ESPONDILOARTROSIS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '72 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR AGUDO CON ESPONDILOARTROSIS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('73 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR CRÓNICO CON ESPONDILOARTROSIS INCIPIENTE ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '73 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR CRÓNICO CON ESPONDILOARTROSIS INCIPIENTE ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('74 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR CRÓNICO CON ESPONDILOARTROSIS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '74 - 724.4 Y 839.2 - SINDROME FACETARIO LUMBAR CRÓNICO CON ESPONDILOARTROSIS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('75 - 724.4 Y 839.2 - LUMBALGIA AGUDA Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '75 - 724.4 Y 839.2 - LUMBALGIA AGUDA Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('76 - 724.4 Y 839.2 - LUMBALGIA CRÓNICA ASOCIADA A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '76 - 724.4 Y 839.2 - LUMBALGIA CRÓNICA ASOCIADA A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('77 - 724.4 Y 839.2 - LUMBALGIA POSTRAUMÁTICA Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '77 - 724.4 Y 839.2 - LUMBALGIA POSTRAUMÁTICA Y SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('78 - 722.10, 738.4 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS ADQUIRIDA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '78 - 722.10, 738.4 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS ADQUIRIDA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('79 - 722.10, 738.4 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS ADQUIRIDA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '79 - 722.10, 738.4 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS ADQUIRIDA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('80 - 722.10, 738.4 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS ADQUIRIDA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '80 - 722.10, 738.4 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS ADQUIRIDA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('81 - 722.73, 756.12 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS LÍTICA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '81 - 722.73, 756.12 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS LÍTICA SIN SIGNOS NEUROLOGICOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('82 - 722.73, 756.12 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS LÍTICA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '82 - 722.73, 756.12 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS LÍTICA CON SIGNOS NEUROLOGICOS DEBILES ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('83 - 722.73, 756.12 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS LÍTICA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '83 - 722.73, 756.12 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESPONDILOLISTESIS LÍTICA CON SIGNOS NEUROLOGICOS FRANCOS ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('84 - 724.02 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESTENOSIS DEL CANAL ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '84 - 724.02 y 839.2 - SINDROME DOLOROSO LUMBAR CON ESTENOSIS DEL CANAL ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('85 - 952.4 - SÍNDORME DE LA CAUDA EQUINA', '85 - 952.4 - SÍNDORME DE LA CAUDA EQUINA'),
    ('86 - 722.83 y 839.2 - SINDROME DE CIRUGÍA LUMBAR FALLIDA ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '86 - 722.83 y 839.2 - SINDROME DE CIRUGÍA LUMBAR FALLIDA ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('87 - 805.4 - FRACTURA DE COMPRESIÒN AGUDA (especificar nivel)', '87 - 805.4 - FRACTURA DE COMPRESIÒN AGUDA (especificar nivel)'),
    ('88 - 733.1 - COLAPSO VERTEBRAL AGUDO (especificar nivel)', '88 - 733.1 - COLAPSO VERTEBRAL AGUDO (especificar nivel)'),
    ('89 - 737.30 - ESCOLIOSIS IDIOPÁTICA', '89 - 737.30 - ESCOLIOSIS IDIOPÁTICA'),
    )
    SACRO_ILIACO_OPCIONES = (
    ('90 - 720.2 y 839.42 - SACROILEITIS AGUDA CON SUBLUXACIONES ASOCIADAS', '90 - 720.2 y 839.42 - SACROILEITIS AGUDA CON SUBLUXACIONES ASOCIADAS'),
    ('91 - 720.2 y 839.42 - SACROILEITIS CRÓNICA CON SUBLUXACIONES ASOCIADAS', '91 - 720.2 y 839.42 - SACROILEITIS CRÓNICA CON SUBLUXACIONES ASOCIADAS'),
    ('92 - 847.3, 839.42 - ESGUINCE SACRO-ILIACO AGUDO, CON DESGARRO MUSCULAR CON SUBLUXACIONES ASOCIADAS', '92 - 847.3, 839.42 - ESGUINCE SACRO-ILIACO AGUDO, CON DESGARRO MUSCULAR CON SUBLUXACIONES ASOCIADAS'),
    ('93 - 847.3, 839.42 - ESGUINCE SACRO-ILIACO AGUDO GRADO I CON SUBLUXACIONES ASOCIADAS', '93 - 847.3, 839.42 - ESGUINCE SACRO-ILIACO AGUDO GRADO I CON SUBLUXACIONES ASOCIADAS'),
    ('94 - 847.3, 839.42 - ESGUINCE SACRO-ILIACO AGUDO GRADO II CON SUBLUXACIONES ASOCIADAS', '94 - 847.3, 839.42 - ESGUINCE SACRO-ILIACO AGUDO GRADO II CON SUBLUXACIONES ASOCIADAS'),
    ('95 - 847.3, 839.42 - ESGUINCE SACRO-ILIACO AGUDO GRADO III CON SUBLUXACIONES ASOCIADAS', '95 - 847.3, 839.42 - ESGUINCE SACRO-ILIACO AGUDO GRADO III CON SUBLUXACIONES ASOCIADAS'),
    ('96 - 805.6 - FRACTURA DEL SACRO', '96 - 805.6 - FRACTURA DEL SACRO'),
    )
    COCCIX_OPCIONES = (
    ('97 - 724.79 - COCCIGODINIA', '97 - 724.79 - COCCIGODINIA'),
    ('98 - 839.41 - SUBLUXACIÓN DEL CÓCCIX', '98 - 839.41 - SUBLUXACIÓN DEL CÓCCIX'),
    ('99 - 847.4 - ESGUINCE DEL CÓCCIX', '99 - 847.4 - ESGUINCE DEL CÓCCIX'),
    ('100 - 724.71 - HIPERMOBILIDAD DEL CÓCCIX', '100 - 724.71 - HIPERMOBILIDAD DEL CÓCCIX'),
    ('101 - 839.41 - DISLOCACÓN TRAUMÁTICA DEL CÓCCIX', '101 - 839.41 - DISLOCACÓN TRAUMÁTICA DEL CÓCCIX'),
    ('102 - 805.6 - FRACTURA DEL CÓCCIX', '102 - 805.6 - FRACTURA DEL CÓCCIX'),
    )
    PELVIS_CADERA_OPCIONES = (
    ('103 - 726.5 - BURSITIS AGUDA (especificar)', '103 - 726.5 - BURSITIS AGUDA (especificar)'),
    ('104 - 726.5 - BURSITIS CRÓNICA (especificar)', '104 - 726.5 - BURSITIS CRÓNICA (especificar)'),
    ('105 - 726.5, 722.73 - BURSITIS CRÓNICA CON SUBLUXACIONES LUMBO-PÉLVICAS (especificar)', '105 - 726.5, 722.73 - BURSITIS CRÓNICA CON SUBLUXACIONES LUMBO-PÉLVICAS (especificar)'),
    ('106 - 716.95 - INFLAMACIÓN ARTICULAR (especificar)', '106 - 716.95 - INFLAMACIÓN ARTICULAR (especificar)'),
    ('107 - 716.95 - INESTABILIDAD DE LA BANDA ILIO-TIBIAL AGUDA', '107 - 716.95 - INESTABILIDAD DE LA BANDA ILIO-TIBIAL AGUDA'),
    ('108 - 716.95 - INESTABILIDAD DE LA BANDA ILIO-TIBIAL CRÓNICA', '108 - 716.95 - INESTABILIDAD DE LA BANDA ILIO-TIBIAL CRÓNICA'),
    ('109 - 719.65, 722.73 - INESTABILIDAD DE LA BANDA ILIO-TIBIAL AGUDA CON SUBLUXACIONES LUMBO-PÉLVICAS', '109 - 719.65, 722.73 - INESTABILIDAD DE LA BANDA ILIO-TIBIAL AGUDA CON SUBLUXACIONES LUMBO-PÉLVICAS'),
    ('110 - 719.65, 722.73 - INESTABILIDAD DE LA BANDA ILIO-TIBIAL CRÓNICA CON SUBLUXACIONES LUMBO-PÉLVICAS', '110 - 719.65, 722.73 - INESTABILIDAD DE LA BANDA ILIO-TIBIAL CRÓNICA CON SUBLUXACIONES LUMBO-PÉLVICAS'),
    ('111 - 848.5 - ESGUINCE  PÉLVICO AGUDO, CON LESION DE TEJIDO MUSCULAR', '111 - 848.5 - ESGUINCE  PÉLVICO AGUDO, CON LESION DE TEJIDO MUSCULAR'),
    ('112 - 848.5 - ESGUINCE PÉLVICO AGUDO, CON LESION DE TEJIDO NO-CONTRACTIL GRADO I', '112 - 848.5 - ESGUINCE PÉLVICO AGUDO, CON LESION DE TEJIDO NO-CONTRACTIL GRADO I '),
    ('113 - 848.5 - ESGUINCE PÉLVICO AGUDO, CON LESION DE TEJIDO NO-CONTRACTIL GRADO II', '113 - 848.5 - ESGUINCE PÉLVICO AGUDO, CON LESION DE TEJIDO NO-CONTRACTIL GRADO II '),
    ('114 - 848.5 - ESGUINCE PÉLVICO AGUDO, CON LESION DE TEJIDO NO-CONTRACTIL GRADO III', '114 - 848.5 - ESGUINCE PÉLVICO AGUDO, CON LESION DE TEJIDO NO-CONTRACTIL GRADO III '),
    ('115 - 848.5 - SÍNDROME DEL PIRIFORME AGUDO', '115 - 848.5 - SÍNDROME DEL PIRIFORME AGUDO'),
    ('116 - 848.5 - SÍNDROME DEL PIRIFORME CRÓNICO', '116 - 848.5 - SÍNDROME DEL PIRIFORME CRÓNICO'),
    ('117 - 355.0, 722.73 - SÍNDROME DEL PIRIFORME AGUDO CON SUBLUXACIONES LUMBO-PÉLVICAS', '117 - 355.0, 722.73 - SÍNDROME DEL PIRIFORME AGUDO CON SUBLUXACIONES LUMBO-PÉLVICAS'),
    ('118 - 355.0, 722.73 - SÍNDROME DEL PIRIFORME CRÓNICO CON SUBLUXACIONES LUMBO-PÉLVICAS', '118 - 355.0, 722.73 - SÍNDROME DEL PIRIFORME CRÓNICO CON SUBLUXACIONES LUMBO-PÉLVICAS'),
    ('119 - 956.0 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO CIÁTICO AGUDO', '119 - 956.0 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO CIÁTICO AGUDO'),
    ('120 - 956.0 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO CIÁTICO CRÓNICO', '120 - 956.0 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO CIÁTICO CRÓNICO'),
    ('121 - 956.0, 722.73 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO CIÁTICO AGUDO CON SUBLUXACIONES LUMBO-PÉLVICAS', '121 - 956.0, 722.73 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO CIÁTICO AGUDO CON SUBLUXACIONES LUMBO-PÉLVICAS'),
    ('122 - 956.0, 722.73 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO CIÁTICO CRÓNICO CON SUBLUXACIONES LUMBO-PÉLVICAS', '122 - 956.0, 722.73 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO CIÁTICO CRÓNICO CON SUBLUXACIONES LUMBO-PÉLVICAS'),
    ('123 - 956.1 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO FEMORAL AGUDO', '123 - 956.1 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO FEMORAL AGUDO'),
    ('124 - 956.1 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO FEMORAL CRÓNICO', '124 - 956.1 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO FEMORAL CRÓNICO'),
    ('125 - 956.1, 722.73 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO FEMORAL AGUDO CON SUBLUXACIONES LUMBO-PÉLVICAS', '125 - 956.1, 722.73 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO FEMORAL AGUDO CON SUBLUXACIONES LUMBO-PÉLVICAS'),
    ('126 - 956.1, 722.73 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO FEMORAL CRÓNICO CON SUBLUXACIONES LUMBO-PÉLVICAS', '126 - 956.1, 722.73 - ATRAPAMIENTO PERIFÉRICO DEL NERVIO FEMORAL CRÓNICO CON SUBLUXACIONES LUMBO-PÉLVICAS'),
    ('127 - 715.95 - COXARTROSIS', '127 - 715.95 - COXARTROSIS'),
    ('128 - 733.42 - NECROSIS AVASCULAR DE LA CADERA', '128 - 733.42 - NECROSIS AVASCULAR DE LA CADERA'),
    ('129 - 355.1 - MERALGIA PARESTÉSICA ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)', '129 - 355.1 - MERALGIA PARESTÉSICA ASOCIADO A SUBLUXACIONES FUNCIONALES DE (anotar los segmentos reportados)'),
    ('129a - 719.45, 719.95, 722.73 - PINZAMIENTO ACETÁBULO-FEMORAL CON SUBLUXACIONES LUMBO-PÉLVICAS', '129a - 719.45, 719.95, 722.73 - PINZAMIENTO ACETÁBULO-FEMORAL CON SUBLUXACIONES LUMBO-PÉLVICAS'),
    )
    CURVATURA_OPCIONES = (
    ('130 - 737.0 - CIFOSIS POSTURAL DEL ADOLESCENTE', '130 - 737.0 - CIFOSIS POSTURAL DEL ADOLESCENTE'),
    ('131 - 737.1 - CIFOSIS ADQUIRIDA', '131 - 737.1 - CIFOSIS ADQUIRIDA'),
    ('132 - 737.10 - CIFOSIS ADQUIRIDA POSTURAL', '132 - 737.10 - CIFOSIS ADQUIRIDA POSTURAL'),
    ('133 - 737.12 - CIFOSIS ADQUIRIDA POSTQUIRÚRGICA', '133 - 737.12 - CIFOSIS ADQUIRIDA POSTQUIRÚRGICA'),
    ('134 - 737.2 - LORDOSIS ADQUIRIDA', '134 - 737.2 - LORDOSIS ADQUIRIDA'),
    ('135 - 737.20 - LORDOSIS ADQUIRIDA POSTURAL', '135 - 737.20 - LORDOSIS ADQUIRIDA POSTURAL'),
    ('136 - 737.21 - LORDOSIS ADQUIRIDA POSTQUIRÚRGICA', '136 - 737.21 - LORDOSIS ADQUIRIDA POSTQUIRÚRGICA'),
    ('137 - 737.3 - CIFOESCOLIOSIS Y ESCOLIOSIS', '137 - 737.3 - CIFOESCOLIOSIS Y ESCOLIOSIS'),
    ('138 - 737.30 - ESCOLIOSIS ADQUIRIDA', '138 - 737.30 - ESCOLIOSIS ADQUIRIDA'),
    ('139 - 754.2 - ESCOLIOSIS CONGÉNITA', '139 - 754.2 - ESCOLIOSIS CONGÉNITA'),
    )
    CEFALEAS_OPCIONES = (
    ('140 - 307.81, 839.08 - CEFALEA TENSIONAL CON SUBLUXACIONES CERVICALES ASOCIADAS', '140 - 307.81, 839.08 - CEFALEA TENSIONAL CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('141 - 339.10, 839.08 - CEFALEA TIPO-TENSIONAL EPISÓDICA CON SUBLUXACIONES CERVICALES ASOCIADAS', '141 - 339.10, 839.08 - CEFALEA TIPO-TENSIONAL EPISÓDICA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('142 - 339.10, 839.08 - CEFALEA TIPO-TENSIONAL CRÓNICA CON SUBLUXACIONES CERVICALES ASOCIADAS', '142 - 339.10, 839.08 - CEFALEA TIPO-TENSIONAL CRÓNICA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('143 - 339.01, 839.08 - CEFALEA EN RACIMO EPISÓDICA CON SUBLUXACIONES CERVICALES ASOCIADAS', '143 - 339.01, 839.08 - CEFALEA EN RACIMO EPISÓDICA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('144 - 339.02, 839.08 - CEFALEA EN RACIMO CRÓNICA CON SUBLUXACIONES CERVICALES ASOCIADAS', '144 - 339.02, 839.08 - CEFALEA EN RACIMO CRÓNICA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('145 - 339.03, 839.08 - HEMICRANIA PAROXÍSTICA EPISÓDICA CON SUBLUXACIONES CERVICALES ASOCIADAS', '145 - 339.03, 839.08 - HEMICRANIA PAROXÍSTICA EPISÓDICA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('146 - 339.04, 839.08 - HEMICRANIA PAROXÍSTICA CRÓNICA CON SUBLUXACIONES CERVICALES ASOCIADAS', '146 - 339.04, 839.08 - HEMICRANIA PAROXÍSTICA CRÓNICA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('147 - 339.21, 839.08 - CEFALEA POST-TRAUMÁTICA AGUDA CON SUBLUXACIONES CERVICALES ASOCIADAS', '147 - 339.21, 839.08 - CEFALEA POST-TRAUMÁTICA AGUDA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('148 - 339.22, 839.08 - CEFALEA POST-TRAUMÁTICA CRÓNICA CON SUBLUXACIONES CERVICALES ASOCIADAS', '148 - 339.22, 839.08 - CEFALEA POST-TRAUMÁTICA CRÓNICA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('149 - 346.7, 839.08 - MIGRAÑA CRÓNICA SIN AURA CON SUBLUXACIONES CERVICALES ASOCIADAS', '149 - 346.7, 839.08 - MIGRAÑA CRÓNICA SIN AURA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('150 - 346.4, 839.08 - MIGRAÑA MENSTRUAL CON SUBLUXACIONES CERVICALES ASOCIADAS', '150 - 346.4, 839.08 - MIGRAÑA MENSTRUAL CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('151 - 346.0, 839.08 - MIGRAÑA SIN AURA CON SUBLUXACIONES CERVICALES ASOCIADAS', '151 - 346.0, 839.08 - MIGRAÑA SIN AURA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    ('152 - 346.1, 839.08 - MIGRAÑA CON AURA CON SUBLUXACIONES CERVICALES ASOCIADAS', '152 - 346.1, 839.08 - MIGRAÑA CON AURA CON SUBLUXACIONES CERVICALES ASOCIADAS'),
    )
    HOMBRO_OPCIONES = (
    ('153 - 726.2 - SÍNDROME DE PINZAMIENTO', '153 - 726.2 - SÍNDROME DE PINZAMIENTO '),
    ('154 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR', '154 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR'),
    ('155 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR CON DESGARRO PARCIAL DEL SUPRAESPINOSO', '155 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR CON DESGARRO PARCIAL DEL SUPRAESPINOSO'),
    ('156 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR CON DESGARRO PARCIAL DEL INFRAESPINOSO', '156 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR CON DESGARRO PARCIAL DEL INFRAESPINOSO'),
    ('157 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR CON DESGARRO PARCIAL DEL SUBESCAPULAR', '157 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR CON DESGARRO PARCIAL DEL SUBESCAPULAR'),
    ('158 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR CON LESIÓN DEL TENDÓN LARGO DEL BÍCEPS', '158 - 726.10 - TENDONITIS AGUDA DEL MANGUITO ROTADOR CON LESIÓN DEL TENDÓN LARGO DEL BÍCEPS'),
    ('159 - 727.61 - RUPTURA TOTAL NO-TRAUMÁTICA DEL MANGUITO ROTADOR', '159 - 727.61 - RUPTURA TOTAL NO-TRAUMÁTICA DEL MANGUITO ROTADOR'),
    ('160 - 726.12 - TENOSINOVITIS BICIPITAL', '160 - 726.12 - TENOSINOVITIS BICIPITAL'),
    ('161 - 726.10 - TENDINOSIS DEL MANGUITO ROTADOR', '161 - 726.10 - TENDINOSIS DEL MANGUITO ROTADOR'),
    ('162 - 726.10 - TENDINOSIS (AGREGAR DE QUE ESTRUCTURA)', '162 - 726.10 - TENDINOSIS (AGREGAR DE QUE ESTRUCTURA)'),
    ('163 - 726.11 - TENDONITIS CALCÍFICA', '163 - 726.11 - TENDONITIS CALCÍFICA'),
    ('164 - 726.10 - BURSITIS AGUDA SUBACROMIODELTOIDEA', '164 - 726.10 - BURSITIS AGUDA SUBACROMIODELTOIDEA'),
    ('165 - 726.10 - BURSITIS AGUDA CORACOIDEA', '165 - 726.10 - BURSITIS AGUDA CORACOIDEA'),
    ('166 - 726.0 - CAPSULITIS ADHESIVA', '166 - 726.0 - CAPSULITIS ADHESIVA'),
    ('167 - 840.2 - INESTABILIDAD (AGREGAR SI SUPERIOR, ANTERIOR, POSTERIOR, INFERIOR O MULTIDIRECCIONAL)', '167 - 840.2 - INESTABILIDAD (AGREGAR SI SUPERIOR, ANTERIOR, POSTERIOR, INFERIOR O MULTIDIRECCIONAL)'),
    ('168 - 839.61 - SUBLUXACION (DISLOCACION) ESTERNOCLAVICULAR', '168 - 839.61 - SUBLUXACION (DISLOCACION) ESTERNOCLAVICULAR'),
    ('169 - 831.1 - SUBLUXACION (DISLOCACION) GLENO-HUMERAL ANTERIOR', '169 - 831.1 - SUBLUXACION (DISLOCACION) GLENO-HUMERAL ANTERIOR'),
    ('170 - 831.2 - SUBLUXACION (DISLOCACION) GLENO-HUMERAL POSTERIOR', '170 - 831.2 - SUBLUXACION (DISLOCACION) GLENO-HUMERAL POSTERIOR'),
    ('171 - 831.3 - SUBLUXACION (DISLOCACION) GLENO-HUMERAL INFERIOR', '171 - 831.3 - SUBLUXACION (DISLOCACION) GLENO-HUMERAL INFERIOR'),
    ('172 - 831.4 - SEPARACIÓN ACROMIO-CLAVICULAR GRADO I', '172 - 831.4 - SEPARACIÓN ACROMIO-CLAVICULAR GRADO I'),
    ('173 - 831.4 - SEPARACIÓN ACROMIO-CLAVICULAR GRADO II', '173 - 831.4 - SEPARACIÓN ACROMIO-CLAVICULAR GRADO II'),
    ('174 - 831.4 - SEPARACIÓN ACROMIO-CLAVICULAR GRADO III', '174 - 831.4 - SEPARACIÓN ACROMIO-CLAVICULAR GRADO III'),
    ('175 - 840.8 - ESGUINCE GRADO I', '175 - 840.8 - ESGUINCE GRADO I'),
    ('176 - 840.8 - ESGUINCE GRADO II', '176 - 840.8 - ESGUINCE GRADO II'),
    ('177 - 840.8 - ESGUINCE GRADO III', '177 - 840.8 - ESGUINCE GRADO III'),
    ('178 - 840.7 - LESION DEL LABRUM GLENOIDEO SUPERIO (SLAP)', '178 - 840.7 - LESION DEL LABRUM GLENOIDEO SUPERIO (SLAP)'),
    )
    CODO_A_MANO_OPCIONES = (
    ('179 - 726.32 - EPICONDILITIS LATERAL AGUDA', '179 - 726.32 - EPICONDILITIS LATERAL AGUDA'),
    ('180 - 726.32 - EPICONDILITIS LATERAL CRÓNICA', '180 - 726.32 - EPICONDILITIS LATERAL CRÓNICA'),
    ('181 - 726.31 - EPICONDILITIS MEDIAL AGUDA', '181 - 726.31 - EPICONDILITIS MEDIAL AGUDA'),
    ('182 - 726.31 - EPICONDILITIS MEDIAL CRÓNICA', '182 - 726.31 - EPICONDILITIS MEDIAL CRÓNICA'),
    ('183 - 726.33 - BURSITIS OLECRANEANA', '183 - 726.33 - BURSITIS OLECRANEANA'),
    ('184 - 719.22 - SINOVITIS DEL CODO', '184 - 719.22 - SINOVITIS DEL CODO'),
    ('185 - TENDINOSIS (AGREGAR DE QUE ESTRUCTURA)', '185 - TENDINOSIS (AGREGAR DE QUE ESTRUCTURA)'),
    ('186 - 841.9 - ESGUINCE AGUDO GI', '186 - 841.9 - ESGUINCE AGUDO GI'),
    ('187 - 841.9 - ESGUINCE AGUDO GII', '187 - 841.9 - ESGUINCE AGUDO GII'),
    ('188 - 841.9 - ESGUINCE AGUDO GIII', '188 - 841.9 - ESGUINCE AGUDO GIII'),
    ('189 - SÍNDROME DEL SUPINADOR', '189 - SÍNDROME DEL SUPINADOR'),
    ('190 - 354.3 - NEURITIS RADIAL PROXIMAL', '190 - 354.3 - NEURITIS RADIAL PROXIMAL'),
    ('191 - 354.2 - NEURITIS CUBITAL PROXIMAL', '191 - 354.2 - NEURITIS CUBITAL PROXIMAL'),
    ('192 - 354.1 - NEURITIS DEL NERVIO MEDIANO PROXIMAL', '192 - 354.1 - NEURITIS DEL NERVIO MEDIANO PROXIMAL'),
    ('193 - 354.0 - SÍNDROME DEL TUNEL CARPIANO', '193 - 354.0 - SÍNDROME DEL TUNEL CARPIANO'),
    ('194 - 354.0 - SÍNDROME DEL TUNEL CARPIANO (NEUROPRAXIA)', '194 - 354.0 - SÍNDROME DEL TUNEL CARPIANO (NEUROPRAXIA)'),
    ('195 - 354.0 - SÍNDROME DEL TUNEL CARPIANO (AXONOTMESIS)', '195 - 354.0 - SÍNDROME DEL TUNEL CARPIANO (AXONOTMESIS)'),
    ('196 - 354.0 - SÍNDROME DEL TUNEL CARPIANO (NEUROTMESIS)', '196 - 354.0 - SÍNDROME DEL TUNEL CARPIANO (NEUROTMESIS)'),
    ('197 - 354.2 - SÍNDROME DEL TUNEL DE GUYON', '197 - 354.2 - SÍNDROME DEL TUNEL DE GUYON'),
    ('198 - 354.2 - SÍNDROME DEL TUNEL DE GUYON (NEUROPRAXIA)', '198 - 354.2 - SÍNDROME DEL TUNEL DE GUYON (NEUROPRAXIA)'),
    ('199 - 354.2 - SÍNDROME DEL TUNEL DE GUYON (AXONOTMESIS)', '199 - 354.2 - SÍNDROME DEL TUNEL DE GUYON (AXONOTMESIS)'),
    ('200 - 354.2 - SÍNDROME DEL TUNEL DE GUYON (NEUROTMESIS)', '200 - 354.2 - SÍNDROME DEL TUNEL DE GUYON (NEUROTMESIS)'),
    ('201 - SÍNDROME DE INTERSECCIÓN', '201 - SÍNDROME DE INTERSECCIÓN'),
    ('202 - 727.5 - SÍNDROME DE DeQUERVAIN', '202 - 727.5 - SÍNDROME DE DeQUERVAIN'),
    ('203 - 728.6 - CONTRACTURA DE DUPUYTREN', '203 - 728.6 - CONTRACTURA DE DUPUYTREN'),
    ('204 - NEURITIS RADIAL SENSORIAL', '204 - NEURITIS RADIAL SENSORIAL'),
    ('205 - TENDINITIS DE LOS EXTENSORES DIGITALES', '205 - TENDINITIS DE LOS EXTENSORES DIGITALES '),
    ('206 - TENDINITIS DE LOS FLEXORES DIGITALES', '206 - TENDINITIS DE LOS FLEXORES DIGITALES '),
    ('207 - 726.4 - BURSITIS DE LA MUÑECA', '207 - 726.4 - BURSITIS DE LA MUÑECA'),
    ('208 - 842.0 - ESGUINCE DE LA MUÑECA GI', '208 - 842.0 - ESGUINCE DE LA MUÑECA GI '),
    ('209 - 842.0 - ESGUINCE DE LA MUÑECA GII', '209 - 842.0 - ESGUINCE DE LA MUÑECA GII '),
    ('210 - 842.0 - ESGUINCE DE LA MUÑECA GIII', '210 - 842.0 - ESGUINCE DE LA MUÑECA GIII'),
    ('211 - 842.12 - ESGUINCE METACARPO-FALANGEO GI', '211 - 842.12 - ESGUINCE METACARPO-FALANGEO GI '),
    ('212 - 842.12 - ESGUINCE METACARPO-FALANGEO GII', '212 - 842.12 - ESGUINCE METACARPO-FALANGEO GII '),
    ('213 - 842.12 - ESGUINCE METACARPO-FALANGEO GIII', '213 - 842.12 - ESGUINCE METACARPO-FALANGEO GIII'),
    ('214 - 842.13 - ESGUINCE INTERFALANGEO GI', '214 - 842.13 - ESGUINCE INTERFALANGEO GI '),
    ('215 - 842.13 - ESGUINCE INTERFALANGEO GII', '215 - 842.13 - ESGUINCE INTERFALANGEO GII '),
    ('216 - 842.13 - ESGUINCE INTERFALANGEO GIII', '216 - 842.13 - ESGUINCE INTERFALANGEO GIII'),
    ('217 - 727.03 - TENOSINOVITIS ESTENOSANTE (dedo en gatillo)', '217 - 727.03 - TENOSINOVITIS ESTENOSANTE (dedo en gatillo)'),
    )
    RODILLA_OPCIONES = (
    ('218 - ESGUINCE AGUDO DE RODILLA GRADO I', '218 - ESGUINCE AGUDO DE RODILLA GRADO I'),
    ('219 - ESGUINCE AGUDO DE RODILLA GRADO II', '219 - ESGUINCE AGUDO DE RODILLA GRADO II'),
    ('220 - ESGUINCE AGUDO DE RODILLA GRADO III', '220 - ESGUINCE AGUDO DE RODILLA GRADO III'),
    ('221 - ESGUINCE AGUDO DE RODILLA GRADO II CON DESGARRO DE MENISCO', '221 - ESGUINCE AGUDO DE RODILLA GRADO II CON DESGARRO DE MENISCO'),
    ('222 - ESGUINCE AGUDO DE RODILLA GRADO III CON DESGARRO DE MENISCO', '222 - ESGUINCE AGUDO DE RODILLA GRADO III CON DESGARRO DE MENISCO'),
    ('223 - 726.65 - BURSITIS PREPATELAR', '223 - 726.65 - BURSITIS PREPATELAR'),
    ('224 - 726.61 - BURSITIS DE LA PES ANSERINA', '224 - 726.61 - BURSITIS DE LA PES ANSERINA'),
    ('225 - 726.69 - BURSITIS SUBPATELAR', '225 - 726.69 - BURSITIS SUBPATELAR'),
    ('226 - 726.63 - BURSITIS DEL LIGAMENTO PERONEAL COLATERAL', '226 - 726.63 - BURSITIS DEL LIGAMENTO PERONEAL COLATERAL'),
    ('227 - 726.62 - BURSITIS DEL LIGAMENTO COLATERAL TIBIAL', '227 - 726.62 - BURSITIS DEL LIGAMENTO COLATERAL TIBIAL'),
    ('228 - 717.7 - CONDROMALACIA PATELAR', '228 - 717.7 - CONDROMALACIA PATELAR'),
    ('229 - SUBLUXACION FIBULO-TIBIAL PROXIMAL', '229 - SUBLUXACION FIBULO-TIBIAL PROXIMAL'),
    ('230 - TENDONITIS PATELAR','230 - TENDONITIS PATELAR'),
    ('231 - PLICA','231 - PLICA'),
    ('232 - DISFUNCIÓN PATELO-FEMORAL','232 - DISFUNCIÓN PATELO-FEMORAL'),
    )
    PRONOSTICO_OPCIONES = (
    ('Reservado', 'Reservado'),
    ('Px1 - Bueno para la vida y para la función.  No es de esperarse que queden secuelas funcionales o estructurales', 'Px1 - Bueno para la vida y para la función.  No es de esperarse que queden secuelas funcionales o estructurales'),
    ('Px2 - Dada las características de las lesiones del paciente, no es posible por ahora descartar secuelas de inestabilidad ligamentaria que ocasionalmente puedan requerir un manejo episódico', 'Px2 - Dada las características de las lesiones del paciente, no es posible por ahora descartar secuelas de inestabilidad ligamentaria que ocasionalmente puedan requerir un manejo episódico'),
    ('Px3 - Dada las características de las lesiones del paciente, es probable que una vez alcanzada la máxima corrección posible sufra recaídas esporádicas que requieran un manejo episódico', 'Px3 - Dada las características de las lesiones del paciente, es probable que una vez alcanzada la máxima corrección posible sufra recaídas esporádicas que requieran un manejo episódico'),
    ('Px4 - Dada la naturaleza del problema del paciente, será necesario mantener un régimen de visitas periódicas de control, revisión o mantenimiento', 'Px4 - Dada la naturaleza del problema del paciente, será necesario mantener un régimen de visitas periódicas de control, revisión o mantenimiento'),
    ('Px5 - Considerando el estado actual del paciente, no es posible establecer un pronóstico definido por el momento, ya que aún no podemos descartar la necesidad de una cirugía', 'Px5 - Considerando el estado actual del paciente, no es posible establecer un pronóstico definido por el momento, ya que aún no podemos descartar la necesidad de una cirugía'),
    )

    pertenece = models.ForeignKey(Paciente, on_delete=models.CASCADE, help_text="seleccione el paciente que corresponde")
    creada = models.DateTimeField(auto_now_add=True )
    modificada = models.DateTimeField(auto_now=True)
    start_time = models.TimeField(help_text='hora de inicio de consulta (hh:mm)')
    end_time = models.TimeField(null=True, blank=True, help_text='hora final de consulta (hh:mm)')
    atiende = models.ForeignKey(Persona, null=True, blank=True,  on_delete=models.CASCADE)
    sesion = models.CharField(max_length=200, blank=True, null=True)
    Padecimiento_actual = RichTextUploadingField()
    Ajuste_de_hoy = RichTextUploadingField()
    general = models.CharField(max_length=200, choices=COLUMNA_GENERAL_OPCIONES, blank=True, default='M99.1 - COMPLEJO DE SUBLUXACION VERTEBRAL', help_text='Escoja una opción')
    cervical = models.CharField(max_length=200, choices=COLUMNA_CERVICAL_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    toraxica = models.CharField(max_length=200, choices=TORAXICA_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    lumbo_sacra = models.CharField(max_length=200, choices=LUMBO_SACRA_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    sacro_iliaco = models.CharField(max_length=200, choices=SACRO_ILIACO_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    coccix = models.CharField(max_length=200, choices=COCCIX_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    pelvis_cadera = models.CharField(max_length=200, choices=PELVIS_CADERA_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    curvatura = models.CharField(max_length=200, choices=CURVATURA_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    cefaleas = models.CharField(max_length=200, choices=CEFALEAS_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    hombro = models.CharField(max_length=200, choices=HOMBRO_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    codo_a_mano = models.CharField(max_length=200, choices=CODO_A_MANO_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    rodilla = models.CharField(max_length=200, choices=RODILLA_OPCIONES, blank=True, default='none', help_text='Escoja una opción')
    pronostico = models.CharField(max_length=200, choices=PRONOSTICO_OPCIONES, blank=True, default='Reservado', help_text='Escoja una opción')
    notas = RichTextUploadingField(blank=True, null=True)
    transoral_neutra = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    transoral_dinamica_derecha = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    transoral_dinamica_izquierda = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    AP_cervical = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    AP_toraxica = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    AP_lumbopelvica = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    lateral_cervical = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    lateral_toraxica = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    lateral_lumbopelvica = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    cervical_extension = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    cervical_flexion = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    stitch_AP = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    stitch_lateral = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    posturometria_frente = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    posturometria_lateral = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    posturometria_posterior = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    scanner = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    extra_1 = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    extra_2 = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)
    foto = ProcessedImageField(upload_to='consulta/%d/%m/%Y/', blank=True, null=True)

    class Meta:
      verbose_name_plural = "consultas"
      ordering = ("-id",)
      get_latest_by = ['creada']

    def __str__(self):
        return str(self.id)
