# Generated by Django 4.0.6 on 2022-12-06 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido_Paterno', models.CharField(max_length=100)),
                ('Apellido_Materno', models.CharField(max_length=100)),
                ('Rol', models.CharField(choices=[('Quiropráctico', 'Quiropráctico'), ('Asistente', 'Asistente'), ('Radiólogo', 'Radiólogo'), ('Capacitación', 'Capacitación'), ('Contabilidad', 'Contabilidad'), ('Administrador', 'Administrador')], default='Quiropràctico', max_length=15)),
                ('Cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('Foto', models.ImageField(blank=True, default='default.jpg', upload_to='medicos/')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personas',
                'verbose_name_plural': 'Persona',
                'ordering': ('-id',),
            },
        ),
    ]
