# Generated by Django 4.0.6 on 2022-12-06 21:23

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Clinica', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=20)),
                ('icono', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='clinica_media/')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Welcome_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan_1', models.CharField(max_length=100)),
                ('slogan_2', models.CharField(max_length=100)),
                ('slogan_3', models.CharField(max_length=100)),
                ('slogan_4', models.CharField(max_length=100)),
                ('imagen_1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='clinica_website/welcome_area/')),
                ('imagen_2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='clinica_website/welcome_area/')),
            ],
        ),
    ]
